config/routes.rb
Rails.application.routes.draw do

  root :to => 'paths#index'

  resources :paths do
    member do
      get 'clients'
      get 'potential_clients'
      get 'map'
      get 'reports'
    end
  end
  resources :branches
  resources :clients
  resources :potential_clients

  devise_for :users

end

app/models/potential_client.rb
class PotentialClient < ActiveRecord::Base
  include Addressable

  has_and_belongs_to_many :path

  def as_json(options = {})
    super({ include: [:address] }.merge(options))
  end

end

app/controllers/potential_clients_controller.rb
class PotentialClientsController < ApplicationController

  before_action :set_potential_client, except:[:index, :create, :new]

  def index
    @potential_clients = PotentialClient.all.page(params[:page]).per(15)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @potential_clients }
    end
  end

  def show
    respond_to do |format|
      format.js
      format.json { render json: @potential_client }
    end
  end

  def edit
  end

  def new
    @potential_client = PotentialClient.new
    @potential_client.build_address
  end

  def create
    @potential_client = PotentialClient.new(potential_client_params)
    if @potential_client.save
      redirect_to potential_clients_path, info: 'Potential client was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    if @potential_client.update_attributes(potential_client_params)
      redirect_to potential_clients_path, info: 'Potential client was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @potential_client.destroy
    redirect_to potential_clients_path, flash: {info: "Potential client was successfully deleted."}
  end

  private

    def set_potential_client
      @potential_client = PotentialClient.find(params[:id])
    end

    def potential_client_params
      params.require(:potential_client).permit(:name, :description, :time_spent, :decision,
      :marketing_agent_name, address_attributes: [:number, :street, :city, :province, :country, :postal_code])
    end
end

app/views/potential_clients/_form.html.erb
<%= errors_for @potential_client %>

<%= form_for @potential_client do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :marketing_agent_name %>
    <%= f.text_field :marketing_agent_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :decision %>
    <%= f.select :decision, ['Accepter', 'En attente', 'Refus'], {}, { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.label :time_spent %>
    <%= f.text_field :time_spent, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.fields_for :address do |ff| %>
      <%= render partial:'partials/address_form', locals:{f: ff} %>
    <% end %>
  </div>

  <%= f.submit class: "btn btn-lg btn-primary btn-block" %>

<% end %>

app/views/potential_clients/_list_item.html.erb
<a class="list-group-item" data-toggle="checkbox">
  <span class="pull-right">
    <%= buidler.check_box %>
  </span>

  <strong class="list-group-item-heading">
    <%= buidler.object.name %>
  </strong>
  <div class="list-group-item-text">
    <i><%= buidler.object.description %></i>
    <% if buidler.object.address %>
    <%= render partial: "partials/address", locals: { address: buidler.object.address } %>
    <% end %>
  </div>

</a>

app/views/potential_clients/_potential_client.html.erb
<i class="fa fa-users"></i> <strong><%= @potential_client.name %></strong><br>

<i><%= @potential_client.description || "N/A" %></i></br>

<%= render @potential_client.address %>
<%= icon_to "glyphicon glyphicon-edit", edit_potential_client_path(@potential_client), "Modifier", class: 'pull-right' %>

app/views/potential_clients/edit.html.erb
<%= panel_for title: 'Editing potential client', size: 6 do %>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
  <div class="panel-footer text-right">
    <%= back_to potential_clients_path %>
  </div>
<% end %>

app/views/potential_clients/index.html.erb
<%= panel_for title: 'Potential clients', size: 12 do %>
  <div class="panel-body">

    <% if @potential_clients.length > 0 %>
      <table class="table table-bordered">
        <tr>
          <th>Name</th>
          <th>Address</th>
          <th>Estimated Time Spent</th>
          <th>Marketing Agent Name</th>
          <th>Decision</th>
          <th>Action</th>
        </tr>
        <% @potential_clients.each do |potential_client| %>
        <tr>
          <td><%= potential_client.name %></td>
          <td><%= render partial: "partials/address", locals: { address: potential_client.address} %></td>
          <td><%= "#{potential_client.time_spent || 0 } min(s)" %></td>
          <td><%= potential_client.marketing_agent_name || "N/A" %></td>
          <td><%= potential_client.decision || "N/A" %></td>
          <td class="text-center">
            <div class="btn-group">
              <%= icon_to 'glyphicon glyphicon-edit', edit_potential_client_path(potential_client), '', class: 'btn btn-warning' %>
              <%= icon_to 'glyphicon glyphicon-remove-circle', potential_client, '', method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            </div>
          </td>
        </tr>
        <% end %>
      </table>
      <div class="text-center">
        <%= paginate @potential_clients %>
      </div>

    <% end %>

    <% if @potential_clients.length == 0 %>
      <p>No potential clients... please click on the button below to create a new potential client.</p>
    <% end %>

  </div>

  <div class="panel-footer text-right">
    <%= link_to 'Add new', new_potential_client_path, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/potential_clients/new.html.erb
<%= panel_for title: 'Add potential client', size: 6 do %>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
  <div class="panel-footer text-right">
    <%= back_to potential_clients_path %>
  </div>
<% end %>

app/views/potential_clients/show.js.erb
infoWindow.setContent("<%= escape_javascript(render @potential_client) %>");