config/routes.rb
Rails.application.routes.draw do

  root :to => 'paths#index'

  resources :paths do
    member do
      get 'clients'
      get 'potential_clients'
      get 'map'
      get 'reports'
    end
  end
  resources :branches
  resources :clients
  resources :potential_clients

  devise_for :users

end

app/models/path.rb
class Path < ActiveRecord::Base

  # Constants
  MODES = %w(DRIVING BICYCLING TRANSIT WALKING)
  PATH_TYPES = %w(Delivery Marketing)

  # Relations
  has_and_belongs_to_many :clients
  has_and_belongs_to_many :potential_clients
  belongs_to :branch
  belongs_to :user

  # Validations
  validates :name, presence:true
  validates :mode, presence:true, inclusion: { in: MODES }
  validates :path_type, presence:true, inclusion: { in: PATH_TYPES }


  validate :max_clients
  validate :max_potential_clients



  # Nested attributes
  accepts_nested_attributes_for :clients, :potential_clients

  def as_json(options = {})
    super({ include: [:clients, :branch, :potential_clients] }.merge(options))
  end


  private

    MAX_WAYPOINT = 8
    # Limit the number of waypoint set by googole API
    def max_clients
      errors.add(:clients, "has more than #{MAX_WAYPOINT} clients.") if clients.size > MAX_WAYPOINT
    end

    def max_potential_clients
      errors.add(:potential_clients, "has more than #{MAX_WAYPOINT} clients.") if potential_clients.size > MAX_WAYPOINT
    end



end

app/controllers/paths_controller.rb
class PathsController < ApplicationController

  # Set custom layout for map action
  layout 'map', only: [:map]

  # This is Devise's authentication
  before_action :authenticate_user!

  before_action :set_path, except: [:index, :create, :new]

  # GET /paths
  # GET /paths.json
  def index
    @paths = current_user.paths.all.page(params[:page]).per(15)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @paths }
    end
  end

  # GET /paths/1
  # GET /paths/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @path }
    end
  end

  # GET /paths/1/clients.json
  def clients
    respond_to do |format|
      format.json { render json: @path.clients }
    end
  end

  # GET /paths/1/potential_clients.json
  def potential_clients
    respond_to do |format|
      format.json { render json: @path.potential_clients }
    end
  end

  def map
    redirect_to edit_path_path(@path), flash:{ alert: 'Path does not have a starting branch.'} unless @path.branch
  end

  # GET /paths/new
  def new
    @path = current_user.paths.build
  end

  # GET /paths/1/edit
  def edit
  end

  # POST /paths
  def create
    @path = current_user.paths.build(path_params)
    if @path.save
      redirect_to map_path_path(@path), flash: {info: 'Path was successfully created.'}
    else
      render action: "new"
    end
  end

  # PUT /paths/1
  def update
    if @path.update_attributes(path_params)
      redirect_to map_path_path(@path), flash: {info: 'Path was successfully updated.'}
    else
      render action: "edit"
    end
  end

  # DELETE /paths/1
  def destroy
    @path.destroy
    redirect_to paths_path, flash: {info: "Path was successfully deleted."}
  end

  private

    def set_path
      @path = current_user.paths.find(params[:id])
    end

    def path_params
      params.require(:path).permit(:name, :mode, :date, :distance,
        :distance_time, :path_type, :branch_id,
        client_ids:[], potential_client_ids:[])
    end


end

app/views/paths/_form.html.erb
<%= errors_for @path %>

<% remote ||= false %>

<%= form_for @path, remote: remote  do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'name',  class: 'form-control' %>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :branch_id %>
        <%= f.select :branch_id, Branch.all.collect {|p| [p.name,p.id]}, {}, { class: 'form-control' } %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :path_type %>
        <%= f.select :path_type, Path::PATH_TYPES, {}, { class: 'form-control' } %>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :date %>
        <%= f.text_field :date, class: 'form-control', data:{ provide: 'datepicker' } %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :mode %>
        <div class="btn-group btn-group-justified" data-toggle="buttons">
          <% Path::MODES.each do |mode| %>
            <%= f.label :mode, class: "btn btn-primary" do %>
              <%= f.radio_button :mode, mode %><%= "<i class='fa fa-#{mode.downcase}'></i>".html_safe %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>


  <div class="row">

    <div class="col-sm-offset-1 col-sm-10">
      <h4>Selected clients <small>(<%= link_to "Add client", new_client_path %>)</small></h4>

      <div class="list-group" data-provide="scrollable">
        <%= f.collection_check_boxes :client_ids, Client.all, :id, :name do |b| %>
          <%= render partial:"clients/list_item", locals: { buidler: b } %>
        <% end %>
      </div>

    </div>

  </div>


  <div class="row">

    <div class="col-sm-offset-1 col-sm-10">
      <h4>Selected potential clients <small>(<%= link_to "Add potential client", new_potential_client_path %>)</small></h4>

      <div class="list-group" data-provide="scrollable">
        <%= f.collection_check_boxes :potential_client_ids, PotentialClient.all, :id, :name do |b| %>
          <%= render partial:"clients/list_item", locals: { buidler: b } %>
        <% end %>
      </div>

    </div>

  </div>



  <%= f.submit class: "btn btn-lg btn-primary btn-block" %>

<% end %>

app/views/paths/edit.html.erb
<%= panel_for title: 'Editing path', size: 6 do %>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
  <div class="panel-footer text-right">
    <%= back_to paths_path %>
  </div>
<% end %>

app/views/paths/index.html.erb
<%= panel_for title: 'My paths', size: 12 do %>
  <div class="panel-body">

    <% if @paths.length > 0 %>
      <table class="table table-bordered">
        <tr>
          <th>Name</th>
          <th>Type</th>
          <th># Clients</th>
          <th># Potential clients</th>
          <th>Actions</th>
        </tr>
        <% @paths.each do |path| %>
        <tr class="<%= "active" if flash[:selected] == path.id %>">
          <td><%= path.name %></td>
          <td><%= path.path_type %></td>
          <td><%= path.clients.length %></td>
          <td><%= path.potential_clients.length %></td>
          <td class="text-center">
            <div class="btn-group">
              <%= icon_to 'glyphicon glyphicon-map-marker', map_path_path(path), '', class: "btn btn-primary" %>
              <%= icon_to 'glyphicon glyphicon-stats', reports_path_path(path), '', class: "btn btn-success" %>
              <%= icon_to 'glyphicon glyphicon-edit', edit_path_path(path), '', class: "btn btn-warning" %>
              <%= icon_to 'glyphicon glyphicon-remove-circle', path, '', method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            </div>
          </td>
        </tr>
        <% end %>
      </table>

      <div class="text-center">
        <%= paginate @paths %>
      </div>

    <% end %>

    <% if @paths.length == 0 %>
      <p>No paths... please click on the button below to create a new path.</p>
    <% end %>

  </div>

  <div class="panel-footer text-right">
    <%= link_to 'Add new', new_path_path, class:'btn btn-primary' %>
  </div>
<% end %>

app/views/paths/map.html.erb
<% content_for :navbar_left do %>
  <li><a data-toggle="collapse" data-target="#path-details"><i class="fa fa-map-marker"></i> <%= @path.name %></a></li>
  <li>
    <div class="btn-group">
      <%= icon_to 'glyphicon glyphicon-stats', reports_path_path(@path), '', class: "btn btn-default navbar-btn" %>
      <button class="btn btn-default navbar-btn" data-toggle="modal" data-target="#directionsModal"><i class="glyphicon glyphicon-list-alt"></i></button>
    </div>
  </li>
<% end %>

<div id="path-details" class="collapse">
  <div data-provide="scrollable" style="padding:5px 5px 20px 5px; height: 600px;">
    <%= render 'form' %>
  </div>
</div>

<div id="map"></div>

<%= content_for :scripts do %>
<script type="text/javascript">

  var map, mapOption, infoWindow, directionsService, directionsDisplay;

  var start_id = <%= @path.branch.id %>;
  var start = new google.maps.LatLng(<%= @path.branch.address.latitude %>, <%= @path.branch.address.longitude %>);

  var mode = "<%= @path.mode %>";
  var path_type = "<%= @path.path_type %>";

  var RED_MARKER = {
    url: "<%= asset_path('spotlight_red.png') %>",
    scaledSize: new google.maps.Size(18, 32)
  },
  BLUE_MARKER = {
    url: "<%= asset_path('spotlight_blue.png') %>",
    scaledSize: new google.maps.Size(18, 32)
  },
  GREEN_MARKER = {
    url: "<%= asset_path('spotlight_green.png') %>",
    scaledSize: new google.maps.Size(18, 32)
  };


  function initialize() {

    directionsService = new google.maps.DirectionsService();
    directionsDisplay = new google.maps.DirectionsRenderer();
    infoWindow        = new google.maps.InfoWindow();

    // Bind print button
    $("#btnPrint").click(print_path);

    // Initialize the default map options hash
    mapOptions = {
      center: new google.maps.LatLng(45.536482, -73.592702),
      zoom: 8
    };

    // Create the map
    map = new google.maps.Map($("#map")[0], mapOptions);

    // Configure direction panel
    directionsDisplay.setMap(map);
    directionsDisplay.setOptions({ suppressMarkers: true });
    directionsDisplay.setPanel($("#directionsPanel")[0]);

    // Load data
    loadMarkers();
  }

  function loadMarkers(){
    var clients = [];
    var potential_clients = [];

    addMarker(start_id, start, {
      markerImage: GREEN_MARKER,
      url: function(id) { return '/branches/' + id; }
    });

    $.when(
      $.getJSON("clients.json", function(data){
        addMarkers(clients, data, {
          markerImage: RED_MARKER,
          url: function(id) { return '/clients/' + id; }
        });
      }),

      $.getJSON("potential_clients.json", function(data){
        addMarkers(potential_clients, data, {
          markerImage: BLUE_MARKER,
          url: function(id) { return '/potential_clients/' + id; }
        });
      })
    ).done(function(){
      if(path_type === "Delivery")
        calcRoute(clients);
      else if(path_type === "Marketing")
        calcRoute(potential_clients);
    });
  }

  function addMarkers(container, addressables, options) {
    $.each(addressables, function(index, el){
      var position = new google.maps.LatLng(el.address.latitude, el.address.longitude);

      container.push(position);

      addMarker(el.id, position, options);
    });
  }

  function addMarker(id, position, options){
    options = $.extend({
      markerImage : RED_MARKER,
      url: function(id){
        return '/clients/' + id
      }
    }, options ||  {});

    var marker = new google.maps.Marker({
      map: map,
      animation: google.maps.Animation.DROP,
      position: position,
      icon: options.markerImage
    });

    google.maps.event.addListener(marker, 'click', function() {
      infoWindow.open(map,marker);
      $.ajax({
        type: 'GET',
        url: options.url(id),
        dataType : 'script'
      });
    });
    return marker;
  }

  function calcRoute(points){

    var waypoints = []
    $.each(points, function(i, el){
      waypoints.push({
        location: el.toString(),
        stopover:true
      });
    });
    var request = {
      origin: start,
      destination: start,
      travelMode: google.maps.TravelMode[mode],
      waypoints: waypoints,
      optimizeWaypoints: true
    };
    directionsService.route(request, function(response, status) {
      if (status == google.maps.DirectionsStatus.OK) {
        directionsDisplay.setDirections(response);
      }
    });
  }


  google.maps.event.addDomListener(window, 'load', initialize);

  function print_path() {
      window.print();
  }

</script>
<% end %>

<%= render partial: 'partials/directions_modal' %>

app/views/paths/new.html.erb
<%= panel_for title: 'Adding path', size: 6 do %>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
  <div class="panel-footer text-right">
    <%= back_to paths_path %>
  </div>
<% end %>

app/views/paths/reports.html.erb
<%= panel_for title: 'Reports', size: 12 do %>
    <div class="panel-body text-center">
        <h1>Delivery path elevation variation</h1>
        <strong>Total distance : <span id="deliveryTotalDistance"></span> KM</strong><br>
        <strong>Total duration : <span id="deliveryTotalDuration"></span> min(s)</strong><br>
        <strong>Total steps : <span id="deliveryTotalSteps"></span></strong><br>
        <div class="row">
          <div class="col-sm-10 col-sm-offset-1" id="deliveryElevation" style="height:400px;"></div>
        </div>

        <h1>Marketing path elevation variation</h1>
        <strong>Total distance : <span id="marketingTotalDistance"></span> KM</strong><br>
        <strong>Total duration : <span id="marketingTotalDuration"></span> min(s)</strong><br>
        <strong>Total steps : <span id="marketingTotalSteps"></span></strong><br>

        <div class="row">
          <div class="col-sm-10 col-sm-offset-1" id="marketingElevation" style="height:400px;"></div>
        </div>

    </div>
    <div class="panel-footer text-right">
      <%= back_to paths_path %>
    </div>
<% end %>


<%= content_for :scripts do %>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD28wyczXQXdz2WOEi7lI46-BAGiMidNb0"></script>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <script type="text/javascript">

    var elevator;

    google.load("visualization", "1", {packages:["corechart"]});

    google.setOnLoadCallback(init);

    function init(){

      elevator = new google.maps.ElevationService();
      directionsService = new google.maps.DirectionsService();

      var start = new google.maps.LatLng(<%= @path.branch.address.latitude %>, <%= @path.branch.address.longitude %>);
      var clients = [];
      var potentialClients = [];

      $.when(
        $.getJSON('clients.json', function(data){ clients = data; }),
        $.getJSON('potential_clients.json', function(data){ potentialClients = data; })
      ).done(function(){

        var generateCoords = function(el, i){
          return new google.maps.LatLng(el.address.latitude, el.address.longitude);
        };

        var clientsCoords = $.map(clients, generateCoords);

        var potentialClientsCoords = $.map(potentialClients, generateCoords);

        generatePath(start, clientsCoords, {
          elevationSelector: "#deliveryElevation",
          distanceSelector: "#deliveryTotalDistance",
          durationSelector: "#deliveryTotalDuration",
          stepsSelector: "#deliveryTotalSteps"
        });

        generatePath(start, potentialClientsCoords, {
          elevationSelector: "#marketingElevation",
          distanceSelector: "#marketingTotalDistance",
          durationSelector: "#marketingTotalDuration",
          stepsSelector: "#marketingTotalSteps"
        });

      });

    }

    function generatePath(start, coords, selectors) {

      var waypoints = $.map(coords, function(el, i){
        return { location: el.toString(), stopover:true };
      });

      var request = {
        origin: start,
        destination: start,
        travelMode: google.maps.TravelMode["<%= @path.mode %>"],
        waypoints: waypoints,
        optimizeWaypoints: true
      };

      directionsService.route(request, function(response, status) {
        if (status == google.maps.DirectionsStatus.OK) {

          var totalDistance = 0;
          var totalDuration = 0;
          var totalSteps = 0;
          var legs = response.routes[0].legs;

          $.each(legs, function(i, el){
            totalDistance += el.distance.value;
            totalDuration += el.duration.value;
            totalSteps += el.steps.length;

          });


          $(selectors.distanceSelector).text((totalDistance / 1000).toFixed(2));
          $(selectors.durationSelector).text((totalDuration / 60).toFixed(2));
          $(selectors.stepsSelector).text(totalSteps);

          var elevCoords = $.map(legs, function(el, i){
            return el.start_location;
          });

          drawElevationChart(elevCoords, selectors);

        }
      });


    }

    function drawElevationChart(coords, selectors) {

      var pathRequest = {
        'path': coords,
        'samples': 256
      }

      // Initiate the path request.
      elevator.getElevationAlongPath(pathRequest, function(results, status){
        if (status == google.maps.ElevationStatus.OK) {

          var data = new google.visualization.DataTable();
          data.addColumn('string', 'Sample');
          data.addColumn('number', 'Elevation (meters)');

          $.each(results, function(i, el){
            data.addRow(['', el.elevation]);
          });


          var options = {
            legend: { position: 'none' }
          };

          var chart = new google.visualization.LineChart($(selectors.elevationSelector).get(0));

          chart.draw(data, options);


        }
      });


    }


  </script>
<% end %>

app/views/paths/show.html.erb
<%= panel_for title: 'Path details', size: 6 do %>
  <div class="panel-body">
  </div>
  <div class="panel-footer text-right">
    <%= back_to paths_path %>
  </div>
<% end %>