config/routes.rb
Rails.application.routes.draw do

  root :to => 'paths#index'

  resources :paths do
    member do
      get 'clients'
      get 'potential_clients'
      get 'map'
      get 'reports'
    end
  end
  resources :branches
  resources :clients
  resources :potential_clients

  devise_for :users

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  include Addressable

  #attr_accessible :name, :description

  has_many :paths

end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController

  before_action :must_be_admin!, except:[:index, :show]

  before_action :set_branch, except: [:index, :create, :new]

  def index
    @branches = Branch.all.page(params[:page]).per(15)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @branches }
    end
  end

  def show
    respond_to do |format|
      format.js
      format.json { render json: @branch }
    end
  end

  def edit
  end

  def new
    @branch = Branch.new
    @branch.build_address
  end

  def create
    @branch = Branch.new(branch_params)

    if @branch.save
      redirect_to branches_path, flash: {info: 'Branch was successfully created.'}
    else
      render action: "new"
    end
  end

  def update
    if @branch.update_attributes(branch_params)
      redirect_to branches_path, flash: {info: 'Branch was successfully updated.'}
    else
      render action: "edit"
    end
  end

  def destroy
    @branch.destroy
    redirect_to branches_path, flash: {info: "Branch was successfully deleted."}
  end

  private

    def set_branch
      @branch = Branch.find(params[:id])
    end

    def branch_params
      params.require(:branch).permit(:name, :description, address_attributes: [
          :number, :street, :city, :province, :country, :postal_code])
    end

    def must_be_admin!
      authenticate_user!
      redirect_to root_path, alert:"You do not have the required permissions to access this content." unless current_user.admin?
    end
end

app/views/branches/_branch.html.erb
<i class="fa fa-briefcase"></i> <strong><%= @branch.name %></strong><br>

<% if !@branch.description.empty? %>
  <i><%= @branch.description %></i></br>
<% end %>
<%= render @branch.address %>
<% if current_user.try :admin? %>
  <%= icon_to "glyphicon glyphicon-edit", edit_branch_path(@branch), "Modifier", class: 'pull-right' %>
<% end %>

app/views/branches/_form.html.erb
<%= errors_for @branch %>

<%= form_for @branch do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.fields_for :address do |ff| %>
      <%= render partial:'partials/address_form', locals:{f: ff} %>
    <% end %>
  </div>

  <%= f.submit class: "btn btn-lg btn-primary btn-block" %>

<% end %>

app/views/branches/edit.html.erb
<%= panel_for title: 'Editing branch', size: 6 do %>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
  <div class="panel-footer text-right">
    <%= back_to branches_path %>
  </div>
<% end %>

app/views/branches/index.html.erb
<%= panel_for title: 'Branches', size: 12 do %>
  <div class="panel-body">

    <% if @branches.length > 0 %>
      <table class="table table-bordered">
        <tr>
          <th>Name</th>
          <th>Address</th>
          <% if current_user.try :admin? %>
            <th>Actions</th>
          <% end %>
        </tr>
        <% @branches.each do |branch| %>
        <tr>
          <td><%= branch.name %></td>
          <td><%= render branch.address %></td>
          <% if current_user.try :admin? %>
            <td class="text-center">
              <div class="btn-group">
                <%= icon_to 'glyphicon glyphicon-edit', edit_branch_path(branch), '', class: 'btn btn-warning' %>
                <%= icon_to 'glyphicon glyphicon-remove-circle', branch, '', method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
              </div>
            </td>
          <% end %>
        </tr>
        <% end %>
      </table>
      <div class="text-center">
        <%= paginate @branches %>
      </div>

    <% end %>

    <% if @branches.length == 0 %>
      <p>No branches... please click on the button below to create a new branch.</p>
    <% end %>

  </div>
  <% if current_user.try :admin? %>
    <div class="panel-footer text-right">
      <%= link_to 'Add new', new_branch_path, class: 'btn btn-primary' %>
    </div>
  <% end %>
<% end %>

app/views/branches/new.html.erb
<%= panel_for title: 'Add branch', size: 6 do %>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
  <div class="panel-footer text-right">
    <%= back_to branches_path %>
  </div>
<% end %>

app/views/branches/show.js.erb
infoWindow.setContent("<%= escape_javascript(render @branch) %>");