config/routes.rb
Rails.application.routes.draw do

  root :to => 'paths#index'

  resources :paths do
    member do
      get 'clients'
      get 'potential_clients'
      get 'map'
      get 'reports'
    end
  end
  resources :branches
  resources :clients
  resources :potential_clients

  devise_for :users

end

app/views/partials/_address.html.erb
<% if address %>
  <address>
    <%= address.number %> <%= address.street %><br />
    <%= address.city %>, <%= address.province %>, <%= address.country %><br />
    <%= address.postal_code %>
  </address>
<% else %>
  N/A
<% end %>

app/views/partials/_address_form.html.erb
<div class="row form-group">
  <div class="col-sm-2">
    <%= f.text_field :number,
    placeholder: '#', class: 'form-control col-sm-2' %>
  </div>
  <div class="col-sm-10">
    <%= f.text_field :street,
    placeholder: 'Street', class: 'form-control col-sm-10' %>
  </div>
</div>
<div class="row form-group">
  <div class="col-sm-6">
    <%= f.text_field :city,
    placeholder: 'City', class: 'form-control' %>
  </div>

  <div class="col-sm-6">
    <%= f.text_field :province,
    placeholder: 'Province/State', class: 'form-control' %>
  </div>

</div>
<div class="row form-group">
  <div class="col-sm-6">
    <%= f.text_field :country,
    placeholder: 'Country', class: 'form-control' %>
  </div>

  <div class="col-sm-6">
    <%= f.text_field :postal_code,
    placeholder: 'Postal code/Zip code', class: 'form-control' %>
  </div>
</div>

app/views/partials/_directions_modal.html.erb
<div class="modal fade" id="directionsModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Directions</h4>
      </div>
      <div class="modal-body">
        <h3><%= @path.name %></h3>

        <div id="directionsPanel"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" id="btnPrint" class="btn btn-primary">Print</button>
      </div>
    </div>
  </div>
</div>

app/views/partials/_flashes.html.erb
<% flash.select {|k,_| !(alert_for k.to_sym).nil? } .each do |type, message| %>
  <div class="alert <%= "alert-#{alert_for type.to_sym}" %>">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/partials/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><strong>ᕕ( ᐛ )ᕗ</strong></a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <%= yield :navbar_left %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= yield :navbar_right %>
        <% if current_user %>
          <li><%= icon_to 'fa fa-map-marker', paths_path, 'My paths' %></li>
        <% end %>
        <li><%= icon_to 'fa fa-users', potential_clients_path, 'Potential clients' %></li>
        <li><%= icon_to 'fa fa-user', clients_path, 'Clients' %></li>
        <li><%= icon_to 'fa fa-briefcase', branches_path, 'Branches' %></li>
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %><span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to 'Sign Out', destroy_user_session_path, method: 'delete' %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Register", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>